### ISSUE TITLE
str.maketrans('', '', punctuation) translation table shouldn't be created repeatedly

### ISSUE THREAD

**Issue by ghost** [zhang587/streaming_word_tokenizer#3]
`str.maketrans('', '', punctuation)` makes a translation table that can be used with `translate`, since the table is used many times (every word in text stream) there's no reason not to make the translation table a class member and create it only once.

**Comment by zhang587** [comment]
I made translation table as a class method per suggested. Could you explain more why emit punctuation doesn't emit the punctuations?

**Comment by ghost** [comment]
I just picked up the changes. what I meant was the part:

```str.maketrans('', '', punctuation)```

should be a class variable. This operation (making a translation table is independent of any token or input so should be precomputed and stashed in the class for repeated use. The same way the regex pattern is done.

The way to test the emit punctuation is to try tokenizing this:

```The cat yawned, flopped, then fell asleep!```

The tokens should be:

```
<The>
<cat>
<yawned>
<,>
<flopped>
<,>
<then> 
<fell>
<asleep>
<!>
```
Maybe the confusion comes from me using the word _emit_ which sounds like _omit_ - yet mean opposites. To emit punctuation means to generate a token for each punctuation character. There are some edge cases to consider like "Dr." should be a single token, despite having a punctuation character.

**Comment by zhang587** [comment]
@darenr With emit punctuations, I extracted the punctuation in a string token. However with the approach I have here, it extracts token <un-american.> to be both ['un', '-', 'american.'] and ['un-american', '.', '']. It is because they way str.partition works, it only takes one separator `string.partition(separator).` Thus it doesn't work when I wanted multiple separators.

Is there a way to collect all the punctuations in a string and partition the string based on those punctuations in one go?

**Comment by ghost** [comment]
Regex can do that sort thing.

**Comment by zhang587** [comment]
Thanks, it worked.
